name: Reusable Workflow
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact
        required: true
        type: string
jobs:
  deploy:
    name: Deploy Project
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls -al
      - name: Output Information
        run: echo "Deploying & uploading..."
