name: Reusable Workflow
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact
        required: true
        type: string
    outputs:
      result:
        description: Some description
        value: ${{ jobs.deploy.outputs.result }}
jobs:
  deploy:
    outputs:
      result: ${{ steps.set-result.outputs.step-result }}
    name: Deploy Project
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ inputs.artifact-name }}
      - name: List files
        run: ls -al
      - name: Output Information
        run: echo "Deploying & uploading..."
      - name: Set result
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT
